# Deploy custom policy definitions, initiatives, and assignments

trigger: none
pr: none

variables:
  AZ_SERVICE_CONNECTION: 'AzureSPN-Katta'
  ENVIRONMENT_NAME: 'alz-dev'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Policy
    displayName: '10-policy'
    jobs:
      - job: DeployPolicy
        displayName: 'Deploy policy set and assignments'
        steps:
          - template: templates/terraform-steps.yml
            parameters:
              workingDirectory: terraform/platform/10-policy
              varFile: environments/dev/policy.tfvars
              planName: 10-policy-dev
              environment: $(ENVIRONMENT_NAME)
              azServiceConnection: $(AZ_SERVICE_CONNECTION)
              apply: true
